services:
  # Backend API Service
  - type: web
    name: pdf-extraction-backend
    env: python
    region: oregon
    plan: free
    branch: main
    rootDir: backend
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && chmod +x setup_dirs.sh && ./setup_dirs.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    pythonVersion: 3.11.9
    healthCheckPath: /health
    envVars:
      - key: GEMINI_API_KEY
        sync: false
  
  # Frontend Static Site
  - type: web
    name: pdf-extraction-frontend
    env: static
    region: oregon
    plan: free
    branch: main
    buildCommand: cd frontend && npm install && npm run build && cp -r dist/* .
    staticPublishPath: ./frontend/dist
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://pdf-extraction-backend.onrender.com/api
